id: 3210bcaf451c471da4a3e0babcdc8e75
initial_creation_type: ocr
source_metadata:
  volumes:
    c76642344e854ed98999e37b1acbff38:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: ''
      total_pages: 1902
      volume_number: 26
