id: DCA800463
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:50:03+00:00'
last_modified: '2022-05-26T11:15:18.303909+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    ae0d:
      image_group_id: I1PD95871
      title: མཐར་ཐུག་འབྲས་བུའི་སྒྲོན་མ།
      total_pages: 1902
      order: 26
      base_file: ae0d.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
